image: golang:latest

stages:
  - test

services:
  - name: bitnami/etcd:latest
    alias: etcd

variables:
  ALLOW_NONE_AUTHENTICATION: "yes"
  ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"

vet:
  stage: test
  script:
    - make vet

unit_test:
  parallel:
    matrix:
      - GO: ["1.18", "1.19"]
  image:
    name: golang:$GO
  stage: test
  variables:
    TESTING_ETCD_ENDPOINTS: "$ETCD_ADVERTISE_CLIENT_URLS"
  script:
    - make test
